### PR TITLE
feat: use `og_image` as image fallback for listing pages

### PR DESCRIPTION
**Pull request by taylrj**

### CODE REVIEW

**Comment by babygoat** [comment]
What is the criteria for displaying the image in listing page/index page? Besides, does the device resolution count?

**Comment by taylrj** [comment]
Displaying `hero_image` is a default setting in listing page/index page.

In some cases which do not have `hero_image` (e.g. [維吾爾人圖輯](https://keystone-preview.twreporter.org/a/photo-the-silence-to-you-one-story-at-a-time)), display `og_image` as fallback.

**Comment by babygoat** [comment]
Can we have the comments here for future reference?

**Comment by taylrj** [comment]
Sure, updated.

**Comment by babygoat** [comment]
LGTM

**Pull request merged**
