### PR TITLE
feat(core, react-components): add fund-raising number

### PR DESCRIPTION
**Pull request by Aylie-Chou**
story: [TWREPORTER-196](https://twreporter-org.atlassian.net/browse/TWREPORTER-196)
- add core constants/fundraising.js: store fund-raising number
  - fund-raising number will update every year
- add fund-raising number in footer

### CODE REVIEW

**Comment by taylrj** [comment]
LGTM

**Comment by taylrj** [comment]
image

Found this when I check this PR by setting `dimensions: iPad` in chrome simulator.
Just wonder is the margin (or padding) between logo and separate line correct ?
Could you help to check on this ?

**Comment by Aylie-Chou** [comment]
Logo & separation line layout do not change in this change.
I would prefer deploy current vertion to staging first, and consult with designers then.

**Comment by taylrj** [comment]
Sure.

**Pull request merged**
