### PR TITLE
Jason/refinement new arch

### PR DESCRIPTION
**Pull request by duidae**
fix https://app.asana.com/0/1202896150264815/1202959962459839/f
companion PR https://github.com/twreporter/twreporter-react/pull/2297

### CODE REVIEW

**Comment by Aylie-Chou** [comment]
It seems that tag page still look the same as current, would tag page change be included in the patch ?
螢幕截圖 2022-11-21 上午10 22 12

**Comment by duidae** [comment]
> It seems that tag page still look the same as current, would tag page change be included in the patch ? 螢幕截圖 2022-11-21 上午10 22 12

下次這個我們可以明確在figma上標出來嗎? 上週三有特別確認過figma上面要修改的地方是不是紅色區塊部分

**Comment by duidae** [comment]
@Aylie-Chou fixed tag page, please have a look, thanks.

**Comment by Aylie-Chou** [comment]
> 下次這個我們可以明確在figma上標出來嗎? 上週三有特別確認過figma上面要修改的地方是不是紅色區塊部分
This discussion could be added in the next demo meeting.

Tag view would need some margin/padding top with RWD.
螢幕截圖 2022-11-22 下午5 09 25

**Comment by duidae** [comment]
> Tag view would need some margin/padding top with RWD.
twreporter-react/ 有一個[PR](https://github.com/twreporter/twreporter-react/pull/2297)要一起launch，然後scroll滑到頂padding會在上面
Screen Shot 2022-11-23 at 3 23 17 PM
Screen Shot 2022-11-23 at 3 22 36 PM

**Review by Aylie-Chou — APPROVED** [review]
LGTM

**Pull request merged**
