### PR TITLE
Jason/figure div avoid break

### PR DESCRIPTION
**Pull request by duidae**
- fix [jira 221](https://twreporter-org.atlassian.net/jira/software/c/projects/TWREPORTER/boards/7?modal=detail&selectedIssue=TWREPORTER-221)
- test article: https://staging.twreporter.org/a/youth-house-rent-greater-taipei-no-choice
- 圖看起來破掉的原因：
ImgContainer在沒跨頁時顯示沒有問題，顯示的機制會參考長寬比，然後用padding-top + overflow的方式來控制圖片高度，一但跨頁parent div斷掉就會把padding顯示成空白，把圖擠下去
- workaround: img parent的div設break-inside: avoid; 
- ref: https://stackoverflow.com/questions/907680/css-printing-avoiding-cut-in-half-divs-between-pages
- ~~PS: 因為dev環境沒有圖，這個PR需要merge到staging比較好測試~~

截圖 2022-03-11 下午1 56 52

### CODE REVIEW

**Review by taylrj — COMMENTED** [review]
Do we need to add `avoid-break` to other components with images (e.g. imageDiff) ?

**Comment by taylrj** [comment]
LGTM

**Review by Aylie-Chou — APPROVED** [review]
LGTM

**Comment by duidae** [comment]
> Do we need to add `.avoid-break` classname to other components with images (e.g. imageDiff) ?

imageDiff放到另外一個ticket  [#262](https://twreporter-org.atlassian.net/browse/TWREPORTER-262)

**Pull request merged**
